// Generated by `tasks/petdex-sync.ps1`.
export type LocalPetdexAvatar = {
  seed: string
  label: string
  spritesheetUrl: string
  remoteSpritesheetUrl?: string
}

export const LOCAL_PETDEX_AVATARS: readonly LocalPetdexAvatar[] = [
  { seed: "47", label: "47", spritesheetUrl: "/pets/47/spritesheet.webp" },
  {
    seed: "acidling",
    label: "Acidling",
    spritesheetUrl: "/pets/acidling/spritesheet.webp",
  },
  { seed: "aku", label: "Aku", spritesheetUrl: "/pets/aku/spritesheet.webp" },
  {
    seed: "asterix",
    label: "Asterix",
    spritesheetUrl: "/pets/asterix/spritesheet.webp",
  },
  {
    seed: "batmeme",
    label: "Batmeme",
    spritesheetUrl: "/pets/batmeme/spritesheet.webp",
  },
  {
    seed: "bitboy",
    label: "BitBoy",
    spritesheetUrl: "/pets/bitboy/spritesheet.webp",
  },
  {
    seed: "bloodseeker",
    label: "Bloodseeker",
    spritesheetUrl: "/pets/bloodseeker/spritesheet.webp",
  },
  {
    seed: "buff-patrick",
    label: "Buff Patrick",
    spritesheetUrl: "/pets/buff-patrick/spritesheet.webp",
  },
  {
    seed: "calcifer",
    label: "Calcifer",
    spritesheetUrl: "/pets/calcifer/spritesheet.webp",
  },
  {
    seed: "canary",
    label: "Canary",
    spritesheetUrl: "/pets/canary/spritesheet.webp",
  },
  {
    seed: "cannibals",
    label: "Cannibals",
    spritesheetUrl: "/pets/cannibals/spritesheet.webp",
  },
  {
    seed: "cartman",
    label: "Cartman",
    spritesheetUrl: "/pets/cartman/spritesheet.webp",
  },
  {
    seed: "cicada",
    label: "Cicada",
    spritesheetUrl: "/pets/cicada/spritesheet.webp",
  },
  {
    seed: "cinder",
    label: "Cinder",
    spritesheetUrl: "/pets/cinder/spritesheet.webp",
  },
  {
    seed: "clippy",
    label: "Clippy",
    spritesheetUrl: "/pets/clippy/spritesheet.webp",
  },
  {
    seed: "crash-bandicoot",
    label: "Crash Bandicoot",
    spritesheetUrl: "/pets/crash-bandicoot/spritesheet.webp",
  },
  {
    seed: "dobby",
    label: "Dobby",
    spritesheetUrl: "/pets/dobby/spritesheet.webp",
  },
  {
    seed: "dude",
    label: "Dude",
    spritesheetUrl: "/pets/dude/spritesheet.webp",
  },
  {
    seed: "einstein",
    label: "Einstein",
    spritesheetUrl: "/pets/einstein/spritesheet.webp",
  },
  {
    seed: "eminem-brisk",
    label: "Eminem Brisk",
    spritesheetUrl: "/pets/eminem-brisk/spritesheet.webp",
  },
  {
    seed: "fangjia",
    label: "FangJia",
    spritesheetUrl: "/pets/fangjia/spritesheet.webp",
  },
  {
    seed: "ghostface",
    label: "Ghostface",
    spritesheetUrl: "/pets/ghostface/spritesheet.webp",
  },
  {
    seed: "gojo",
    label: "Gojo",
    spritesheetUrl: "/pets/gojo/spritesheet.webp",
  },
  {
    seed: "goku",
    label: "Goku",
    spritesheetUrl: "/pets/goku/spritesheet.webp",
  },
  {
    seed: "homie",
    label: "Homie",
    spritesheetUrl: "/pets/homie/spritesheet.png",
  },
  {
    seed: "invincible-mark",
    label: "invincible-mark",
    spritesheetUrl: "/pets/invincible-mark/spritesheet.webp",
  },
  {
    seed: "itachi",
    label: "Itachi",
    spritesheetUrl: "/pets/itachi/spritesheet.webp",
  },
  {
    seed: "jane",
    label: "Jane",
    spritesheetUrl: "/pets/jane/spritesheet.webp",
  },
  {
    seed: "johnny",
    label: "Johnny",
    spritesheetUrl: "/pets/johnny/spritesheet.webp",
  },
  {
    seed: "kebo",
    label: "Kebo",
    spritesheetUrl: "/pets/kebo/spritesheet.webp",
  },
  {
    seed: "kiki",
    label: "Kiki",
    spritesheetUrl: "/pets/kiki/spritesheet.webp",
  },
  {
    seed: "kratos-norse",
    label: "Kratos Norse",
    spritesheetUrl: "/pets/kratos-norse/spritesheet.webp",
  },
  {
    seed: "leafspark",
    label: "Leafspark",
    spritesheetUrl: "/pets/leafspark/spritesheet.webp",
  },
  {
    seed: "luffy",
    label: "Luffy",
    spritesheetUrl: "/pets/luffy/spritesheet.webp",
  },
  {
    seed: "masked-manager",
    label: "Masked Manager",
    spritesheetUrl: "/pets/masked-manager/spritesheet.webp",
  },
  {
    seed: "mini-dark-lord",
    label: "Mini Dark Lord",
    spritesheetUrl: "/pets/mini-dark-lord/spritesheet.webp",
  },
  {
    seed: "mochi",
    label: "Mochi",
    spritesheetUrl: "/pets/mochi/spritesheet.webp",
  },
  {
    seed: "nezukocoder",
    label: "NezukoCoder",
    spritesheetUrl: "/pets/nezukocoder/spritesheet.webp",
  },
  {
    seed: "noir-webling",
    label: "Noir Webling",
    spritesheetUrl: "/pets/noir-webling/spritesheet.webp",
  },
  {
    seed: "peter",
    label: "Peter",
    spritesheetUrl: "/pets/peter/spritesheet.webp",
  },
  {
    seed: "pickle-rick",
    label: "Pickle Rick",
    spritesheetUrl: "/pets/pickle-rick/spritesheet.webp",
  },
  {
    seed: "popeye",
    label: "Popeye",
    spritesheetUrl: "/pets/popeye/spritesheet.webp",
  },
  {
    seed: "prism",
    label: "Prism",
    spritesheetUrl: "/pets/prism/spritesheet.webp",
  },
  {
    seed: "rimuru",
    label: "Rimuru",
    spritesheetUrl: "/pets/rimuru/spritesheet.webp",
  },
  {
    seed: "scorpion",
    label: "Scorpion",
    spritesheetUrl: "/pets/scorpion/spritesheet.webp",
  },
  {
    seed: "spyro",
    label: "Spyro",
    spritesheetUrl: "/pets/spyro/spritesheet.png",
  },
  {
    seed: "totoro",
    label: "Totoro",
    spritesheetUrl: "/pets/totoro/spritesheet.webp",
  },
  {
    seed: "vault-boy",
    label: "Vault Boy",
    spritesheetUrl: "/pets/vault-boy/spritesheet.webp",
  },
  {
    seed: "violet-mage",
    label: "Violet Mage",
    spritesheetUrl: "/pets/violet-mage/spritesheet.webp",
  },
  {
    seed: "wall-e-baby",
    label: "Wall-E Baby",
    spritesheetUrl: "/pets/wall-e-baby/spritesheet.webp",
  },
  {
    seed: "wojak",
    label: "Wojak",
    spritesheetUrl: "/pets/wojak/spritesheet.webp",
  },
  {
    seed: "yamcha",
    label: "Yamcha",
    spritesheetUrl: "/pets/yamcha/spritesheet.webp",
  },
  {
    seed: "zoro",
    label: "Zoro",
    spritesheetUrl: "/pets/zoro/spritesheet.webp",
  },
  {
    seed: "kyojuro-rengoku",
    label: "炼狱杏寿郎",
    spritesheetUrl: "/pets/kyojuro-rengoku/spritesheet.webp",
  },
] as const
