export const AVAILABLE_FONTS = [
  "Arial",
  "Verdana",
  "Helvetica",
  "Tahoma",
  "Trebuchet MS",
  "Times New Roman",
  "Georgia",
  "Garamond",
  "Courier New",
  "Brush Script MT",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Oswald",
  "Source Sans Pro",
  "Raleway",
  "PT Sans",
  "Merriweather",
  "Nunito",
  "Playfair Display",
  "Ubuntu",
  "Poppins",
  "Quicksand",
  "Libre Baskerville",
  "Bitter",
  "Fjalla One",
  "Anton",
  "Josefin Sans",
  "Lobster",
  "Pacifico",
  "Dancing Script",
  "Satisfy",
  "Courgette",
  "Bree Serif",
  "Archivo Narrow",
  "Arvo",
  "Exo",
  "Asap",
  "Indie Flower",
  "Shadows Into Light",
  "Coming Soon",
  "Fredoka One",
  "Comfortaa",
  "Caveat",
  "Amatic SC",
  "Permanent Marker",
  "Orbitron",
  "Inter",
  "Outfit",
].sort()
